# Generated by Django 4.0.5 on 2022-11-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
