# Generated by Django 4.1.4 on 2022-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='updating_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
